language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t ferdiaz8/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true ferdiaz8/react-test npm test

after_success:
    - docker build -t ferdiaz8/multi-client ./client
    - docker build -t ferdiaz8/multi-nginx ./nginx
    - docker build -t ferdiaz8/multi-server ./server
    - docker build -t ferdiaz8/multi-worker ./worker
    
    #Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    #Take those images and push them to docker hub
    - docker push ferdiaz8/multi-client
    - docker push ferdiaz8/multi-nginx
    - docker push ferdiaz8/multi-server
    - docker push ferdiaz8/multi-worker


    deploy:
        edge: true
        provider: elasticbeanstalk
        region: us-east-2
        app: multi-docker
        env: MultiDocker-env
        bucket_name: elasticbeanstalk-us-east-2-350599941254
        bucket_path: docker-multi
        on:
            branch: master
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key: $AWS_SECRET_KEY
        